### ISSUE TITLE
Unhandled exception appeared.

### ISSUE THREAD

**Issue by StYankovsky** [gammu/wammu#65] opened 2017-11-10 09:38 UTC
Unhandled exception appeared. If you want to help improving this program, please report this together with description how this situation has happened. Please report in english, otherwise you will be most likely told to translate you report to english later.

Traceback:
  File "/usr/lib/python2.7/dist-packages/Wammu/Main.py", line 983, in OnProgress
    del self.progress

Exception: AttributeError: progress

[wammu-crash-XeuOoa.log](https://github.com/gammu/wammu/files/1460829/wammu-crash-XeuOoa.log)

OS (uname -a): Linux Zedd-W520 4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Hard: Lenovo W520 (Core i7, 16Gb mem)
Modem (lsusb): Bus 002 Device 007: ID 0bdb:1911 Ericsson Business Mobile Networks BV

**Comment by nijel** [comment] 2017-11-17 14:54
Duplicate of #25

**Closed by nijel** 2017-11-17 14:54 UTC
