### ISSUE TITLE
Can not write contacts to the SIM, the process hangs with a prompt "Writing contact..."

### ISSUE THREAD

**Issue by Pavel-Sayekat** [gammu/wammu#32] opened 2016-06-04 08:24 UTC
Can not write contacts to the SIM, the process hangs with a prompt "Writing contact..."
 File "/usr/lib/python2.7/dist-packages/Wammu/Main.py", line 1324, in OnEdit
    self.EditContact(evt.data)
  File "/usr/lib/python2.7/dist-packages/Wammu/Main.py", line 1166, in EditContact
    if v['MemoryType'] != backup['MemoryType'] or  v['Location'] != backup['Location']:

Exception: ValueError: Missing key in dictionary: Location

Debug log has been automatically saved to /tmp/wammu-crash-nck8bz.log, you are strongly encouraged to include it in bugreport.

[wammu-crash-nck8bz.txt](https://github.com/gammu/wammu/files/298750/wammu-crash-nck8bz.txt)

**Comment by nijel** [comment] 2016-06-22 13:40
Duplicate of https://github.com/gammu/wammu/issues/23, please upgrade python-gammu.

**Closed by nijel** 2016-06-22 13:40 UTC
